name = "QuadOsc"
uuid = "a9cf478a-2615-4838-ad15-fb8b30e5064d"
authors = ["Henry Gebhardt <hsggebhardt@gmail.com>"]
version = "0.1.1"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
QuadGK = "2"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SpecialFunctions"]
